image: Visual Studio 2019
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
 cmd: dotnet pack --output ..\..\
artifacts:
  - path: '*.nupkg'