image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_test:
#- cmd: dotnet pack --output ..\..\
- cmd: msbuild /t:pack /p:IncludeSymbols=true /p:Configuration=Release src\DotNetStarter.Web\DotNetStarter.Web.csproj
artifacts:
  - path: '*.nupkg'